# Step 1: Base image (Node.js official)
FROM node:22-alpine

# Step 2: Set working directory
WORKDIR /app

# Build backend then frontend

# Step 3: Install backend dependencies
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Step 4: Install frontend dependencies
COPY frontend/package.json frontend/yarn.lock ./frontend/
RUN yarn install --frozen-lockfile

COPY . .

ENV PORT=3000

EXPOSE 5000

CMD ["yarn", "dev"]
